name: OpenPolitics
tagline: An open source plan for the UK. Take control, and create the future you want.

collections:
  policies:
    output: true
    permalink: /manifesto/policies/:path/

defaults:
  -
    scope:
      path: ""
      type: "policies"
    values:
      layout: "new_policy"  

exclude: ["vendor"]

kramdown:
  auto_ids: true

baseurl: /

data_source: data

gems:
  - jemoji
  
defaults:
-
  scope:
    path: "manifesto"
    type: "pages"
  values:
    layout: "policy"
-
  scope:
    path: "manifesto/constituencies"
    type: "pages"
  values:
    layout: "local_policy"
